# Generated by Django 2.2.4 on 2020-02-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
    ]
